# F03/CRvH — Panel D: fGSEA Stacked Bar Chart (Pathway Enrichment)
#
# Dodged Up/Down bars per contrast, stacked by database.
# Stack order bottom->top (largest->smallest): GO:BP, Reactome, Hallmark, KEGG, GO Slim.
# Reads fGSEA cache generated by panel_C.R — run that first.
# Contrasts: Cancer_vs_Healthy, Training_CR
# Outputs: panel_D_fgsea_MAIN.pdf/.png

setwd(rprojroot::find_rstudio_root_file())
source("04_Figures/F03/a_script/style.R")

library(dplyr)
library(readr)
library(tidyr)
library(ggplot2)
library(patchwork)

RPT <- "04_Figures/F03/CRvH/b_reports"
DAT <- "04_Figures/F03/CRvH/c_data"

# Read fGSEA cache from panel_C
fgsea_cache <- file.path(DAT, "01_panel_C_fgsea_results.csv")
stopifnot(file.exists(fgsea_cache))
fgsea_raw <- read_csv(fgsea_cache, show_col_types = FALSE)

pdf_device <- get_pdf_device()

# Stack order: largest DB at bottom (darkest) -> smallest at top (lightest)
DB_ORDER          <- c("GO:BP", "Reactome", "Hallmark", "KEGG", "GO Slim")
DISPLAY_CONTRASTS <- c("Cancer_vs_Healthy", "Training_CR")

# --- Color gradients: darkest at bottom -> lightest at top ---
red_shades  <- colorRampPalette(c("#B2182B", "#D6604D", "#F4A582"))(length(DB_ORDER))
blue_shades <- colorRampPalette(c("#2166AC", "#4393C3", "#92C5DE"))(length(DB_ORDER))
names(red_shades)  <- DB_ORDER
names(blue_shades) <- DB_ORDER

# --- Count sig pathways per contrast x direction x database ---
count_df <- fgsea_raw |>
  filter(!is.na(padj), padj < 0.05,
         database %in% DB_ORDER, contrast %in% DISPLAY_CONTRASTS) |>
  mutate(direction = ifelse(NES > 0, "Up", "Down")) |>
  group_by(contrast, direction, database) |>
  summarise(count = n(), .groups = "drop")

# Fill missing combos with 0
full_grid <- expand_grid(
  contrast  = DISPLAY_CONTRASTS,
  direction = c("Up", "Down"),
  database  = DB_ORDER
)
count_df <- full_grid |>
  left_join(count_df, by = c("contrast", "direction", "database")) |>
  mutate(count = replace_na(count, 0))

count_df$database <- factor(count_df$database, levels = DB_ORDER)

# --- Manual x positions for dodged bars ---
BAR_W     <- 0.30
DODGE_GAP <- 0.08
ctr_centers <- setNames(seq_along(DISPLAY_CONTRASTS), DISPLAY_CONTRASTS)

count_df <- count_df |>
  mutate(
    x_center = ctr_centers[contrast] +
      ifelse(direction == "Up", -(BAR_W / 2 + DODGE_GAP / 2),
                                  BAR_W / 2 + DODGE_GAP / 2)
  )

# --- Compute cumulative y positions for stacking ---
count_df <- count_df |>
  arrange(contrast, direction, factor(database, levels = DB_ORDER)) |>
  group_by(contrast, direction) |>
  mutate(
    ymax = cumsum(count),
    ymin = ymax - count
  ) |>
  ungroup()

# Assign fill colors
count_df <- count_df |>
  mutate(fill = ifelse(direction == "Up",
                       red_shades[as.character(database)],
                       blue_shades[as.character(database)]))

# --- Bar-top totals ---
bar_tops <- count_df |>
  group_by(contrast, direction, x_center) |>
  summarise(total = sum(count), .groups = "drop")

# --- Plot dimensions (shorter: only 2 contrasts) ---
PC_W <- 120
PC_H <- 120
lbl_sz <- scale_text(BASE_COUNT, PC_W)

# --- Background rects ---
bg_rects <- tibble(
  xmin = seq_along(DISPLAY_CONTRASTS) - 0.5,
  xmax = seq_along(DISPLAY_CONTRASTS) + 0.5,
  fill = CONTRAST_COLORS[DISPLAY_CONTRASTS]
)

p <- ggplot() +
  # Contrast background shading
  geom_rect(data = bg_rects,
            aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf),
            fill = bg_rects$fill, alpha = 0.20,
            color = "grey70", linewidth = 0.2) +
  # Stacked database segments
  geom_rect(data = count_df,
            aes(xmin = x_center - BAR_W / 2, xmax = x_center + BAR_W / 2,
                ymin = ymin, ymax = ymax),
            fill = count_df$fill, color = "white", linewidth = 0.25) +
  # Total count labels above bars
  geom_text(data = bar_tops |> filter(total > 0),
            aes(x = x_center, y = total, label = total),
            vjust = -0.3, size = lbl_sz + 0.2, fontface = "bold",
            color = "grey20") +
  scale_x_continuous(
    breaks = seq_along(DISPLAY_CONTRASTS),
    labels = CTR_SHORT[DISPLAY_CONTRASTS],
    expand = expansion(mult = 0.10)
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.12))) +
  coord_cartesian(clip = "off") +
  labs(title = "Pathways Enriched Up/Down (CRvH)",
       subtitle = sprintf("fGSEA | Hallmark + GO Slim + GO:BP + KEGG + Reactome | per-database BH | %d sig / %d tested",
                          sum(count_df$count),
                          nrow(fgsea_raw |> filter(database %in% DB_ORDER, contrast %in% DISPLAY_CONTRASTS))),
       x = NULL, y = "Significant pathways (padj < 0.05)",
       tag = "D") +
  FIG_THEME +
  theme(
    axis.text.x        = element_text(angle = 35, hjust = 1,
                                      size = FIG_AXIS_TEXT - 0.5),
    legend.position    = "none",
    panel.grid.major.x = element_blank(),
    plot.margin        = margin(5, 8, 2, 5)
  )

# --- Legend: horizontal layout below the plot ---
key_sq_sz <- 2.5
key_txt   <- lbl_sz - 0.8

grey_shades <- colorRampPalette(c("grey30", "grey75"))(length(DB_ORDER))
names(grey_shades) <- DB_ORDER

key_df <- tibble(
  label = c("Up", "Down", DB_ORDER),
  fill  = c(unname(DIR_COLORS[c("Up", "Down")]),
            grey_shades[DB_ORDER]),
  x     = seq_along(c("Up", "Down", DB_ORDER)),
  section = c("Direction", "Direction",
              rep("Database", length(DB_ORDER)))
)

p_key <- ggplot(key_df) +
  geom_point(aes(x = x, y = 0), shape = 22, size = key_sq_sz,
             fill = key_df$fill, color = "grey30", stroke = 0.4) +
  geom_text(aes(x = x, y = -0.4, label = label),
            size = key_txt, color = "grey20") +
  annotate("text", x = 1.5, y = 0.6, label = "Direction",
           size = key_txt, fontface = "bold", color = "grey20") +
  annotate("text", x = mean(seq(3, 2 + length(DB_ORDER))), y = 0.6,
           label = "Database",
           size = key_txt, fontface = "bold", color = "grey20") +
  scale_y_continuous(limits = c(-1, 1)) +
  theme_void() +
  theme(plot.margin = margin(0, 2, 2, 2))

p_combined <- p / p_key + plot_layout(heights = c(6, 1))

ggsave(file.path(RPT, "panel_D_fgsea_MAIN.pdf"), p_combined,
       width = PC_W, height = PC_H, units = "mm", device = pdf_device)
ggsave(file.path(RPT, "panel_D_fgsea_MAIN.png"), p_combined,
       width = PC_W, height = PC_H, units = "mm", dpi = 300)
message("F03/CRvH Panel D (stacked fGSEA) saved")
